handling
handleException: anError 
	error := anError