handling
handleException: anError
	^ self new handleException: anError